---
- name: Upgrade nodejs and npm to latest
  hosts: pi
  remote_user: pi
  become: true

  tasks:
    #- name: Install node-red
    #  become: yes
    #  apt:
    #    name: "{{item}}"
    #  with_items:
    #    - nodered
    #    - npm

    #- name: Remove lists for stretch
    #  shell: "rm -rf /var/lib/apt/lists/*"
    #  become: yes

    - name: Download update-nodejs-and-nodered
      get_url:
        url: https://raw.githubusercontent.com/node-red/raspbian-deb-package/master/resources/update-nodejs-and-nodered
        dest: /usr/bin/update-nodejs-and-nodered
        mode: 0777

    - name: Upgrade nodejs and nodered
      shell: "yes|/usr/bin/update-nodejs-and-nodered"

  
    - name: Install node-red modules
      npm: 
        name: "{{ item }}"
        path: /home/pi/.node-red
        global: yes
      with_items:
        - node-red-contrib-timecheck
        - node-red-contrib-time-range-switch

    - name: start and enable nodered service
      systemd:
        name: nodered
        enabled: yes
        state: started
      become: true